include:
    - Sources            # Inspect all Swift files under "Source/"
exclude:
    - '**Spec.swift'   # Ignore Swift files that end in "Tests"
    - Example/Pods       # Ignore Swift files under "Source/Pods/"